{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <allure_1.test_feature_story.TestLogin object at 0x00000169C07D4F08>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:38: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1603879160177, "stop": 1603879160177}, {"name": "点击密码", "status": "passed", "start": 1603879160177, "stop": 1603879160177}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"C:\\bpp\\hgwc_work\\10.18_pytest\\code\\pythondemo\\allure_1\\test_feature_story.py\", line 38, in test_login_failure\n    assert '1' == 1\n"}, "start": 1603879160177, "stop": 1603879160177}], "attachments": [{"name": "stdout", "source": "6c043248-1034-4c39-a373-556282580fd1-attachment.txt", "type": "text/plain"}], "start": 1603879160177, "stop": 1603879160178, "uuid": "b8a2da30-a654-43c1-b0ff-d449833b8624", "historyId": "a58c5550e5c40eb80abda2e84e87077a", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-E5BR4RC"}, {"name": "thread", "value": "1688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}